import json
import os

notebook_path = r"C:\Users\USER\Desktop\OJAAI\Prescription_Donut_Training.ipynb"

if not os.path.exists(notebook_path):
    print("Notebook not found")
    exit(1)

with open(notebook_path, 'r', encoding='utf-8') as f:
    notebook = json.load(f)

print(f"Loaded notebook with {len(notebook['cells'])} cells.")

# 1. Update Step 3 (Download Dataset)
# We find the cell that imports kagglehub
for cell in notebook['cells']:
    if cell['cell_type'] == 'code' and any('kagglehub' in line for line in cell['source']):
        print("Found Step 3 download cell. Replacing...")
        cell['source'] = [
            "import os\n",
            "import shutil\n",
            "from pathlib import Path\n",
            "\n",
            "# 1. Clone the Hugging Face dataset containing the annotated prescriptions\n",
            "print(\"Cloning Hugging Face dataset chinmays18/medical-prescription-dataset...\")\n",
            "repo_url = \"https://huggingface.co/datasets/chinmays18/medical-prescription-dataset\"\n",
            "repo_dir = Path(\"/content/medical-prescription-dataset\")\n",
            "\n",
            "if repo_dir.exists():\n",
            "    print(\"Dataset repository already cloned. Skipping clone.\")\n",
            "else:\n",
            "    !git clone {repo_url} {repo_dir}\n",
            "    print(\"✅ Dataset cloned successfully.\")"
        ]

# 2. Update Step 4 Preprocessing Cell 1
# We find the cell that contains Setup directories
for cell in notebook['cells']:
    if cell['cell_type'] == 'code' and any('Setup directories' in line for line in cell['source']):
        print("Found Step 4 cell 1. Replacing...")
        cell['source'] = [
            "import os\n",
            "import json\n",
            "import re\n",
            "import shutil\n",
            "from pathlib import Path\n",
            "\n",
            "# ── Setup directories ────────────────────────────────────────────────────────\n",
            "TRAIN_DIR = Path(\"/content/donut_train_data\")\n",
            "IMAGES_DIR = TRAIN_DIR / \"images\"\n",
            "TRAIN_DIR.mkdir(parents=True, exist_ok=True)\n",
            "IMAGES_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "def parse_header_field(gt_str: str, field_name: str) -> str:\n",
            "    \"\"\"Extract a simple field from the ground truth string using regex.\"\"\"\n",
            "    pattern = rf\"{field_name}:\\s*(.*?)\\s*(?:doctor_name:|clinic_name:|clinic_address:|patient_name:|patient_age:|patient_gender:|date:|medications:|signature:|<\\/s>|$)\"\n",
            "    match = re.search(pattern, gt_str, re.I | re.S)\n",
            "    return match.group(1).strip() if match else \"\"\n",
            "\n",
            "def parse_gt_medications(gt_str: str):\n",
            "    \"\"\"Extract medications list and dosage fields.\"\"\"\n",
            "    meds_match = re.search(\n",
            "        r\"medications:\\s*(.*?)\\s*(?:signature:|date:|doctor_name:|patient_name:|patient_age:|clinic_name:|clinic_address:|<\\/s>)\",\n",
            "        gt_str,\n",
            "        re.S\n",
            "    )\n",
            "    if not meds_match:\n",
            "        return []\n",
            "    meds_block = meds_match.group(1)\n",
            "    items = [item.strip() for item in meds_block.split(\"- \") if item.strip()]\n",
            "\n",
            "    medications = []\n",
            "    i = 0\n",
            "    while i < len(items):\n",
            "        item = items[i]\n",
            "        is_drug = False\n",
            "        match = re.search(r\"(\\d+(?:\\.\\d+)?)\\s*(mg|mcg|ml|g|iu|units?|puffs?|drops?)\\b\", item, re.I)\n",
            "        if match:\n",
            "            is_drug = True\n",
            "        else:\n",
            "            bare_match = re.search(r\"\\b(\\d+)\\b\", item)\n",
            "            if bare_match:\n",
            "                first_word = item.split()[0].lower() if item.split() else \"\"\n",
            "                if first_word not in [\"with\", \"at\", \"after\", \"before\", \"every\", \"once\", \"twice\", \"three\", \"four\", \"take\", \"in\", \"on\"]:\n",
            "                    is_drug = True\n",
            "\n",
            "        if is_drug:\n",
            "            parts = re.split(r\"(\\d+(?:\\.\\d+)?)\\s*(mg|mcg|ml|g|iu|units?|puffs?|drops?)\\b\", item, flags=re.I)\n",
            "            drug_name = parts[0].strip()\n",
            "            dosage_val = float(parts[1]) if len(parts) > 1 else None\n",
            "            dosage_unit = parts[2].lower() if len(parts) > 2 else None\n",
            "\n",
            "            frequency = None\n",
            "            if i + 1 < len(items):\n",
            "                next_item = items[i+1]\n",
            "                next_is_drug = False\n",
            "                if re.search(r\"(\\d+(?:\\.\\d+)?)\\s*(mg|mcg|ml|g|iu|units?|puffs?|drops?)\\b\", next_item, re.I):\n",
            "                    next_is_drug = True\n",
            "\n",
            "                if not next_is_drug:\n",
            "                    frequency = next_item\n",
            "                    i += 1\n",
            "\n",
            "            medications.append({\n",
            "                \"raw_drug_name\": drug_name,\n",
            "                \"dosage_value\": dosage_val,\n",
            "                \"dosage_unit\": dosage_unit,\n",
            "                \"frequency\": frequency\n",
            "            })\n",
            "        i += 1\n",
            "    return medications"
        ]

# 3. Update Step 4 Preprocessing Cell 2
# We find the cell that contains build_metadata_from_images
for cell in notebook['cells']:
    if cell['cell_type'] == 'code' and any('build_metadata_from_images' in line for line in cell['source']):
        print("Found Step 4 cell 2. Replacing...")
        cell['source'] = [
            "# Format Hugging Face annotations into metadata.jsonl\n",
            "repo_dir = Path(\"/content/medical-prescription-dataset\")\n",
            "train_ann_dir = repo_dir / \"train\" / \"annotations\"\n",
            "train_img_dir = repo_dir / \"train\" / \"images\"\n",
            "\n",
            "if not train_ann_dir.exists():\n",
            "    # Fallback to test dir if train dir doesn't exist\n",
            "    train_ann_dir = repo_dir / \"test\" / \"annotations\"\n",
            "    train_img_dir = repo_dir / \"test\" / \"images\"\n",
            "\n",
            "json_files = sorted(list(train_ann_dir.glob(\"*.json\")))\n",
            "print(f\"Processing {len(json_files)} annotations from {train_ann_dir}...\")\n",
            "\n",
            "entries = []\n",
            "count = 0\n",
            "\n",
            "for file_path in json_files:\n",
            "    try:\n",
            "        with open(file_path, \"r\", encoding=\"utf-8\") as f:\n",
            "            data = json.load(f)\n",
            "        \n",
            "        gt_str = data.get(\"ground_truth\", \"\")\n",
            "        if not gt_str:\n",
            "            continue\n",
            "            \n",
            "        doctor_name = parse_header_field(gt_str, \"doctor_name\")\n",
            "        clinic_name = parse_header_field(gt_str, \"clinic_name\")\n",
            "        patient_name = parse_header_field(gt_str, \"patient_name\")\n",
            "        patient_age = parse_header_field(gt_str, \"patient_age\")\n",
            "        patient_gender = parse_header_field(gt_str, \"patient_gender\")\n",
            "        prescription_date = parse_header_field(gt_str, \"date\")\n",
            "        \n",
            "        doctor_reg = \"\"\n",
            "        reg_match = re.search(r\"\\b(?:mci|reg|nmc)[\\s.:-]*([A-Z0-9/-]+)\", doctor_name, re.I)\n",
            "        if reg_match:\n",
            "            doctor_reg = reg_match.group(1)\n",
            "            \n",
            "        medications_list = parse_gt_medications(gt_str)\n",
            "        medications = []\n",
            "        for med in medications_list:\n",
            "            medications.append({\n",
            "                \"drug_name\": med.get(\"raw_drug_name\") or \"\",\n",
            "                \"dosage_value\": med.get(\"dosage_value\"),\n",
            "                \"dosage_unit\": med.get(\"dosage_unit\"),\n",
            "                \"frequency\": med.get(\"frequency\"),\n",
            "                \"freq_per_day\": None,\n",
            "                \"duration_days\": None,\n",
            "                \"route\": \"oral\"\n",
            "            })\n",
            "            \n",
            "        structured_gt = {\n",
            "            \"doctor_name\": doctor_name if doctor_name else None,\n",
            "            \"doctor_reg\": doctor_reg if doctor_reg else None,\n",
            "            \"clinic_name\": clinic_name if clinic_name else None,\n",
            "            \"patient_name\": patient_name if patient_name else None,\n",
            "            \"patient_age\": patient_age if patient_age else None,\n",
            "            \"patient_gender\": patient_gender if patient_gender else None,\n",
            "            \"prescription_date\": prescription_date if prescription_date else None,\n",
            "            \"diagnosis\": None,\n",
            "            \"medications\": medications\n",
            "        }\n",
            "        \n",
            "        # Copy image file to TRAIN_DIR/images\n",
            "        img_name = file_path.stem + \".png\"\n",
            "        src_img = train_img_dir / img_name\n",
            "        dest_img = IMAGES_DIR / img_name\n",
            "        \n",
            "        if src_img.exists():\n",
            "            shutil.copy2(src_img, dest_img)\n",
            "            entries.append({\n",
            "                \"file_name\": f\"images/{img_name}\",\n",
            "                \"ground_truth\": json.dumps(structured_gt)\n",
            "            })\n",
            "            count += 1\n",
            "    except Exception as e:\n",
            "        print(f\"Error processing {file_path.name}: {e}\")\n",
            "\n",
            "# Write metadata.jsonl\n",
            "metadata_path = TRAIN_DIR / \"metadata.jsonl\"\n",
            "with open(metadata_path, 'w', encoding='utf-8') as f:\n",
            "    for entry in entries:\n",
            "        f.write(json.dumps(entry) + '\\n')\n",
            "\n",
            "print(f\"\u2705 Preprocessing complete. Wrote {count} non-empty entries to {metadata_path}\")\n",
            "print(f\"   Sample ground truth: {entries[0]['ground_truth']}\")"
        ]

# 4. Update Step 7 Hyperparameters cell
# We find the cell that contains EPOCHS = 10
for cell in notebook['cells']:
    if cell['cell_type'] == 'code' and any('EPOCHS        = 10' in line for line in cell['source']):
        print("Found Step 7 hyperparameters cell. Updating...")
        cell['source'] = [
            "TRAIN_DIR = Path(\"/content/donut_train_data\")\n",
            "\n",
            "# Optional: Mount Google Drive to persist checkpoints across sessions\n",
            "USE_DRIVE = False  # Set to True to enable Drive mount\n",
            "if USE_DRIVE:\n",
            "    from google.colab import drive\n",
            "    drive.mount('/content/drive')\n",
            "    OUTPUT_DIR = Path(\"/content/drive/MyDrive/donut-rx-finetuned\")\n",
            "else:\n",
            "    OUTPUT_DIR = Path(\"/content/donut-rx-finetuned\")\n",
            "\n",
            "# ── Training Hyperparameters ────────────────────────────────────────────────\n",
            "EPOCHS        = 5     # 5 epochs is sufficient for convergence on 800+ samples\n",
            "BATCH_SIZE    = 1     # Reduced to 1 to prevent CUDA OutOfMemory on T4 GPU\n",
            "GRAD_ACCUM    = 8     # Effective batch = 1 * 8 = 8\n",
            "LEARNING_RATE = 2e-5\n",
            "MAX_LENGTH    = 512\n",
            "# ───────────────────────────────────────────────────────────────────────────\n",
            "\n",
            "# Create Dataset\n",
            "train_dataset = PrescriptionDataset(\n",
            "    dataset_path=TRAIN_DIR,\n",
            "    processor=processor,\n",
            "    max_length=MAX_LENGTH,\n",
            ")\n",
            "print(f\"\u2705 Training dataset: {len(train_dataset)} samples\")\n",
            "\n",
            "# Training Arguments\n",
            "training_args = Seq2SeqTrainingArguments(\n",
            "    output_dir=str(OUTPUT_DIR),\n",
            "    num_train_epochs=EPOCHS,\n",
            "    per_device_train_batch_size=BATCH_SIZE,\n",
            "    gradient_accumulation_steps=GRAD_ACCUM,\n",
            "    learning_rate=LEARNING_RATE,\n",
            "    weight_decay=0.01,\n",
            "    warmup_steps=50,\n",
            "    logging_steps=5,\n",
            "    save_steps=100,\n",
            "    save_total_limit=3,\n",
            "    predict_with_generate=True,\n",
            "    fp16=True,              # Use half-precision for T4 GPU speedup\n",
            "    dataloader_num_workers=2,\n",
            "    report_to=\"none\",       # Disable W&B / TensorBoard\n",
            "    load_best_model_at_end=False,\n",
            ")\n",
            "\n",
            "# Instantiate HF Trainer\n",
            "trainer = Seq2SeqTrainer(\n",
            "    model=model,\n",
            "    args=training_args,\n",
            "    train_dataset=train_dataset,\n",
            ")\n",
            "\n",
            "print(f\"\u2705 Trainer configured. Starting training for {EPOCHS} epochs...\")"
        ]

# 5. Update Step 9 Inference Test Cell
# We find the cell that contains sample_images = list((TRAIN_DIR / "images").glob("*.jpg"))
for cell in notebook['cells']:
    if cell['cell_type'] == 'code' and any('sample_images = list((TRAIN_DIR / "images").glob("*.jpg"))' in line for line in cell['source']):
        print("Found Step 9 inference test cell. Updating...")
        cell['source'] = [
            "import re\n",
            "\n",
            "def donut_sequence_to_json(seq: str) -> dict:\n",
            "    \"\"\"Parse Donut XML-style output back to a Python dict.\"\"\"\n",
            "    result = {}\n",
            "    # Find all top-level tags\n",
            "    pattern = r'<s_(\\w+)>(.*?)</s_\\1>'\n",
            "    for match in re.finditer(pattern, seq, re.DOTALL):\n",
            "        key = match.group(1)\n",
            "        value = match.group(2).strip()\n",
            "        # Check if it's a list (contains <s_el> tags)\n",
            "        if '<s_el>' in value:\n",
            "            items = []\n",
            "            for el_match in re.finditer(r'<s_el>(.*?)</s_el>', value, re.DOTALL):\n",
            "                items.append(donut_sequence_to_json(el_match.group(1)))\n",
            "            result[key] = items\n",
            "        else:\n",
            "            result[key] = value if value else None\n",
            "    return result\n",
            "\n",
            "\n",
            "# Pick a sample image from the training set (they are PNGs now)\n",
            "sample_images = list((TRAIN_DIR / \"images\").glob(\"*.png\"))\n",
            "if sample_images:\n",
            "    test_image_path = sample_images[0]\n",
            "    print(f\"Testing inference on: {test_image_path.name}\")\n",
            "    \n",
            "    # Load and process\n",
            "    model.eval()\n",
            "    model.to(\"cuda\")\n",
            "    \n",
            "    test_image = Image.open(test_image_path).convert(\"RGB\")\n",
            "    pixel_values = processor(test_image, return_tensors=\"pt\").pixel_values.to(\"cuda\")\n",
            "    \n",
            "    decoder_input_ids = torch.tensor([[model.config.decoder_start_token_id]]).to(\"cuda\")\n",
            "    \n",
            "    with torch.no_grad():\n",
            "        outputs = model.generate(\n",
            "            pixel_values,\n",
            "            decoder_input_ids=decoder_input_ids,\n",
            "            max_length=512,\n",
            "            pad_token_id=processor.tokenizer.pad_token_id,\n",
            "            eos_token_id=processor.tokenizer.eos_token_id,\n",
            "            use_cache=True,\n",
            "            num_beams=1,\n",
            "            do_sample=False,\n",
            "        )\n",
            "    \n",
            "    output_seq = processor.batch_decode(outputs, skip_special_tokens=False)[0]\n",
            "    output_seq = output_seq.replace(processor.tokenizer.eos_token, \"\").replace(processor.tokenizer.pad_token, \"\").strip()\n",
            "    \n",
            "    print(f\"\\nRaw output sequence:\\n{output_seq}\")\n",
            "    \n",
            "    parsed = donut_sequence_to_json(output_seq)\n",
            "    print(f\"\\nParsed JSON output:\")\n",
            "    print(json.dumps(parsed, indent=2))\n",
            "else:\n",
            "    print(\"No images found for inference test.\")"
        ]

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)

print("✅ Successfully patched Prescription_Donut_Training.ipynb!")
